# Generated by Django 5.1.4 on 2025-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
