# Generated by Django 5.1.4 on 2025-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_service', '0002_alter_payment_session_id_alter_payment_session_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
