# Generated by Django 5.1.4 on 2025-01-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_service', '0003_payment_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
