# Generated by Django 5.1.4 on 2025-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_service', '0004_payment_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_product_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
