name: Test

on:
  pull_request:
    branches:
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Set testing environment
        run: echo "DJANGO_ENV=local" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "PGDATA=${{ secrets.PGDATA }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose exec -T library sh -c "python manage.py test"

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
